In [ ]:
import pickle
def read_pickles(name):
	if '.pickle' in name:
		name = name[:-7]
	with open(name + ".pickle", "rb") as f:
		pickle_file = pickle.load(f)
	f.close()

	return pickle_file

def read_labels(f):
	file = open(f)
	top_labels = list()
	for line in file:
		top_labels.append(line[:-1])

	return top_labels
labels = read_labels('/content/62_previous_host_labels.txt')

for label in labels:
  print(label)

Nitrosative Stress
Fermented Foods and Beverages
Gestational Weight Gain
Antineoplastic Agents, Immunological
Sustainable Development
Oligodendrocyte Precursor Cells
Healthy Aging
Marijuana Use
Salpingo-oophorectomy
Long-Acting Reversible Contraception
Patient Health Questionnaire
Platelet-Rich Fibrin
Circulating Tumor DNA
Nephroureterectomy
PC-3 Cells
Carbapenem-Resistant Enterobacteriaceae
Receptors, Chimeric Antigen
Procalcitonin
Radiofrequency Ablation
Proteostasis
Dietary Sugars
Tobacco Smoking
Flexural Strength
Deep Learning
Mental Status and Dementia Tests
Whole Genome Sequencing
Liquid Biopsy
Cigarette Smoking
Work Engagement
Mycobacterium abscessus
Smokers
Frailty
Wildfires
Mice, Knockout, ApoE
Whole Exome Sequencing
THP-1 Cells
Saline Solution
Greenhouse Gases
Circulating MicroRNA
Progression-Free Survival
Anti-Citrullinated Protein Antibodies
Treatment Adherence and Compliance
Pyrolysis
Nutrients
Sexual Health
Pain, Procedural
Dietary Exposure
Academic Performance
Latent Cla

In [ ]:

final_similarities=dict()
for j in os.listdir('/content/'):
  if 'from' in j:
    similarities= read_pickles('/content/'+j.split('.')[0])
    for key in similarities.keys():
      if (key in labels):
        if (key not in final_similarities.keys()):
          final_similarities[key] = list()
        for pair in similarities[key]:
          final_similarities[key].append(np.max(pair[0]))
      if (key == 'Flexural Strength'):
        print(len(final_similarities[key]))
        
  
    






428
898
1310
1880
2410
2903
3480
3951
4515


In [ ]:
import numpy as np
from sklearn import mixture
from sklearn.metrics import confusion_matrix

threshold_dict=dict()
count=0
clf = mixture.GaussianMixture(n_components=2, covariance_type='full', max_iter = 100, random_state = 24)
for key in final_similarities.keys():
  if (key in labels):
    print(key)
    X_train = np.array(final_similarities[key])
    clf.fit(X_train.reshape(-1,1))
    print(clf.means_ , '\nMidpoint value: ', np.round(np.mean(clf.means_),4))
    print()
    threshold_dict[key] = np.mean(clf.means_)
    count+=1


print(count)
    
    

Flexural Strength
[[0.78355101]
 [0.81797224]] 
Midpoint value:  0.8008

Intraepithelial Lymphocytes
[[0.8493362 ]
 [0.83818161]] 
Midpoint value:  0.8438

Nephroureterectomy
[[0.78792746]
 [0.81252173]] 
Midpoint value:  0.8002

Water Pipe Smoking
[[0.80214326]
 [0.77917885]] 
Midpoint value:  0.7907

Oligodendrocyte Precursor Cells
[[0.88884809]
 [0.85024986]] 
Midpoint value:  0.8695

Mycobacterium abscessus
[[0.8577915 ]
 [0.89221257]] 
Midpoint value:  0.875

Salpingo-oophorectomy
[[0.88600643]
 [0.83503665]] 
Midpoint value:  0.8605

Long-Acting Reversible Contraception
[[0.85152348]
 [0.87916671]] 
Midpoint value:  0.8653

Nitrosative Stress
[[0.82982811]
 [0.80988816]] 
Midpoint value:  0.8199

Anti-Citrullinated Protein Antibodies
[[0.87068751]
 [0.86386102]] 
Midpoint value:  0.8673

Extracellular Polymeric Substance Matrix
[[0.85584563]
 [0.83495124]] 
Midpoint value:  0.8454

Proteostasis
[[0.79351043]
 [0.77976091]] 
Midpoint value:  0.7866

Saline Solution
[[0.77339931]
 

In [ ]:
for key in threshold_dict:
  print(key)
  print(threshold_dict[key])



Flexural Strength
0.8007616272469859
Intraepithelial Lymphocytes
0.8437589016569952
Nephroureterectomy
0.8002245978435939
Water Pipe Smoking
0.7906610534561063
Oligodendrocyte Precursor Cells
0.8695489784148789
Mycobacterium abscessus
0.8750020330100026
Salpingo-oophorectomy
0.8605215401261901
Long-Acting Reversible Contraception
0.8653450940342088
Nitrosative Stress
0.819858136360166
Anti-Citrullinated Protein Antibodies
0.8672742623412555
Extracellular Polymeric Substance Matrix
0.8453984358456943
Proteostasis
0.7866356650474866
Saline Solution
0.7909918508023732
Gestational Weight Gain
0.8156576583314405
Wildfires
0.780591895752756
Receptors, Chimeric Antigen
0.843503083831167
Work Engagement
0.7563330423724477
Sustainable Development
0.753453070957051
Procalcitonin
0.7655815620075948
Pain, Procedural
0.7985000919976066
Platelet-Rich Fibrin
0.8521644082247817
Patient Health Questionnaire
0.8113066547876386
Shift Work Schedule
0.7893340730718572
PC-3 Cells
0.8382233600125341
Treatmen

In [ ]:
with open('gmms_threshold.pickle', 'wb') as f:
        pickle.dump(threshold_dict, f)
        f.close()